# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 499)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("background-color: rgb(0, 60, 117);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 60, 491, 421))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("QTabWidget::pane { \n"
"    border: 2px solid #e20019;\n"
"}\n"
"/*QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"  background: rgb(245, 245, 245);; \n"
"} */\n"
"/*QTabBar::tab{\n"
"    background-color: native;\n"
"}*/\n"
"/*QTabBar::tab {\n"
"background-color: lightgray;\n"
"  border: 1px solid #e20019; \n"
"padding: 10 px;\n"
"} */\n"
"/*QTabBar::tab:hover{\n"
"    background-color: native;\n"
"}*/\n"
"\n"
"QTabWidget::tab-bar {\n"
"\n"
"    }\n"
"\n"
"    QTabBar::tab {\n"
"     background: gray;\n"
"     color: black;\n"
"border: 1px solid #e20019;\n"
"     padding: 5px;\n"
"    }\n"
"\n"
"    QTabBar::tab:selected {\n"
"     background: lightgray;\n"
"    }\n"
"\n"
"\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setStyleSheet("")
        self.tab_1.setObjectName("tab_1")
        self.start_button = QtWidgets.QPushButton(self.tab_1)
        self.start_button.setGeometry(QtCore.QRect(140, 180, 151, 41))
        self.start_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(self.tab_1)
        self.stop_button.setGeometry(QtCore.QRect(140, 240, 151, 41))
        self.stop_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.stop_button.setObjectName("stop_button")
        self.connect_button = QtWidgets.QPushButton(self.tab_1)
        self.connect_button.setGeometry(QtCore.QRect(140, 30, 151, 41))
        self.connect_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connect_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.connect_button.setObjectName("connect_button")
        self.disconnect_button = QtWidgets.QPushButton(self.tab_1)
        self.disconnect_button.setGeometry(QtCore.QRect(140, 90, 151, 41))
        self.disconnect_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.disconnect_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.disconnect_button.setObjectName("disconnect_button")
        self.status = QtWidgets.QLabel(self.tab_1)
        self.status.setGeometry(QtCore.QRect(330, 60, 41, 41))
        self.status.setText("")
        self.status.setObjectName("status")
        self.status_2 = QtWidgets.QLabel(self.tab_1)
        self.status_2.setGeometry(QtCore.QRect(330, 210, 41, 41))
        self.status_2.setText("")
        self.status_2.setObjectName("status_2")
        self.start_button.raise_()
        self.stop_button.raise_()
        self.disconnect_button.raise_()
        self.connect_button.raise_()
        self.status.raise_()
        self.status_2.raise_()
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 461, 421))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(350, 200, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(150, 110, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.p2_y = QtWidgets.QLineEdit(self.tab)
        self.p2_y.setGeometry(QtCore.QRect(180, 140, 57, 23))
        self.p2_y.setStyleSheet("color: rgb(255, 255, 255);")
        self.p2_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p2_y.setObjectName("p2_y")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(70, 10, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.p3_z = QtWidgets.QLineEdit(self.tab)
        self.p3_z.setGeometry(QtCore.QRect(280, 170, 57, 23))
        self.p3_z.setStyleSheet("color: rgb(255, 255, 255);")
        self.p3_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p3_z.setObjectName("p3_z")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(250, 140, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.cs_name = QtWidgets.QLineEdit(self.tab)
        self.cs_name.setGeometry(QtCore.QRect(70, 50, 251, 23))
        self.cs_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.cs_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cs_name.setObjectName("cs_name")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.cs_res = QtWidgets.QLineEdit(self.tab)
        self.cs_res.setGeometry(QtCore.QRect(100, 260, 81, 23))
        self.cs_res.setStyleSheet("color: rgb(255, 255, 255);")
        self.cs_res.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cs_res.setObjectName("cs_res")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(180, 80, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(150, 140, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.t1_y = QtWidgets.QLineEdit(self.tab)
        self.t1_y.setGeometry(QtCore.QRect(180, 230, 57, 23))
        self.t1_y.setStyleSheet("color: rgb(255, 255, 255);")
        self.t1_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t1_y.setObjectName("t1_y")
        self.p3_x = QtWidgets.QLineEdit(self.tab)
        self.p3_x.setGeometry(QtCore.QRect(80, 170, 57, 23))
        self.p3_x.setStyleSheet("color: rgb(255, 255, 255);")
        self.p3_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p3_x.setObjectName("p3_x")
        self.p4_x = QtWidgets.QLineEdit(self.tab)
        self.p4_x.setGeometry(QtCore.QRect(80, 200, 57, 23))
        self.p4_x.setStyleSheet("color: rgb(255, 255, 255);")
        self.p4_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p4_x.setObjectName("p4_x")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(150, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.p1_z = QtWidgets.QLineEdit(self.tab)
        self.p1_z.setGeometry(QtCore.QRect(280, 110, 57, 23))
        self.p1_z.setStyleSheet("color: rgb(255, 255, 255);")
        self.p1_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p1_z.setObjectName("p1_z")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(350, 110, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.p2_z = QtWidgets.QLineEdit(self.tab)
        self.p2_z.setGeometry(QtCore.QRect(280, 140, 57, 23))
        self.p2_z.setStyleSheet("color: rgb(255, 255, 255);")
        self.p2_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p2_z.setObjectName("p2_z")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(250, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(150, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(250, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.p1_y = QtWidgets.QLineEdit(self.tab)
        self.p1_y.setGeometry(QtCore.QRect(180, 110, 57, 23))
        self.p1_y.setStyleSheet("color: rgb(255, 255, 255);")
        self.p1_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p1_y.setObjectName("p1_y")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(350, 140, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.cs_dist = QtWidgets.QLineEdit(self.tab)
        self.cs_dist.setGeometry(QtCore.QRect(90, 80, 81, 23))
        self.cs_dist.setStyleSheet("color: rgb(255, 255, 255);")
        self.cs_dist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cs_dist.setObjectName("cs_dist")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.t1_z = QtWidgets.QLineEdit(self.tab)
        self.t1_z.setGeometry(QtCore.QRect(280, 230, 57, 23))
        self.t1_z.setStyleSheet("color: rgb(255, 255, 255);")
        self.t1_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t1_z.setObjectName("t1_z")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(250, 230, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.p1_x = QtWidgets.QLineEdit(self.tab)
        self.p1_x.setGeometry(QtCore.QRect(80, 110, 57, 23))
        self.p1_x.setStyleSheet("color: rgb(255, 255, 255);")
        self.p1_x.setInputMask("")
        self.p1_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p1_x.setObjectName("p1_x")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(250, 110, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(150, 230, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setGeometry(QtCore.QRect(350, 170, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 50, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.t1_x = QtWidgets.QLineEdit(self.tab)
        self.t1_x.setGeometry(QtCore.QRect(80, 230, 57, 23))
        self.t1_x.setStyleSheet("color: rgb(255, 255, 255);")
        self.t1_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t1_x.setObjectName("t1_x")
        self.p2_x = QtWidgets.QLineEdit(self.tab)
        self.p2_x.setGeometry(QtCore.QRect(80, 140, 57, 23))
        self.p2_x.setStyleSheet("color: rgb(255, 255, 255);")
        self.p2_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p2_x.setObjectName("p2_x")
        self.p3_y = QtWidgets.QLineEdit(self.tab)
        self.p3_y.setGeometry(QtCore.QRect(180, 170, 57, 23))
        self.p3_y.setStyleSheet("color: rgb(255, 255, 255);")
        self.p3_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p3_y.setObjectName("p3_y")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(350, 230, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.p4_y = QtWidgets.QLineEdit(self.tab)
        self.p4_y.setGeometry(QtCore.QRect(180, 200, 57, 23))
        self.p4_y.setStyleSheet("color: rgb(255, 255, 255);")
        self.p4_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p4_y.setObjectName("p4_y")
        self.cs_add_button = QtWidgets.QPushButton(self.tab)
        self.cs_add_button.setGeometry(QtCore.QRect(60, 300, 291, 41))
        self.cs_add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cs_add_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.cs_add_button.setObjectName("cs_add_button")
        self.p4_z = QtWidgets.QLineEdit(self.tab)
        self.p4_z.setGeometry(QtCore.QRect(280, 200, 57, 23))
        self.p4_z.setStyleSheet("color: rgb(255, 255, 255);")
        self.p4_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p4_z.setObjectName("p4_z")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.cs_scan_button = QtWidgets.QPushButton(self.tab)
        self.cs_scan_button.setGeometry(QtCore.QRect(60, 360, 291, 41))
        self.cs_scan_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cs_scan_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.cs_scan_button.setObjectName("cs_scan_button")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.cs_name_handler = QtWidgets.QLineEdit(self.tab_4)
        self.cs_name_handler.setGeometry(QtCore.QRect(80, 70, 251, 23))
        self.cs_name_handler.setStyleSheet("color: rgb(255, 255, 255);")
        self.cs_name_handler.setText("")
        self.cs_name_handler.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cs_name_handler.setObjectName("cs_name_handler")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setGeometry(QtCore.QRect(20, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_4)
        self.label_40.setGeometry(QtCore.QRect(20, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.cs_show_secs = QtWidgets.QLineEdit(self.tab_4)
        self.cs_show_secs.setGeometry(QtCore.QRect(90, 120, 41, 23))
        self.cs_show_secs.setStyleSheet("color: rgb(255, 255, 255);")
        self.cs_show_secs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cs_show_secs.setObjectName("cs_show_secs")
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(140, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.cs_set_button = QtWidgets.QPushButton(self.tab_4)
        self.cs_set_button.setGeometry(QtCore.QRect(10, 180, 121, 51))
        self.cs_set_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cs_set_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.cs_set_button.setObjectName("cs_set_button")
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        self.label_38.setGeometry(QtCore.QRect(70, 20, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.cs_show_button = QtWidgets.QPushButton(self.tab_4)
        self.cs_show_button.setGeometry(QtCore.QRect(140, 180, 121, 51))
        self.cs_show_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cs_show_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.cs_show_button.setObjectName("cs_show_button")
        self.cs_remove_button = QtWidgets.QPushButton(self.tab_4)
        self.cs_remove_button.setGeometry(QtCore.QRect(270, 180, 121, 51))
        self.cs_remove_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cs_remove_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.cs_remove_button.setObjectName("cs_remove_button")
        self.cs_list_button = QtWidgets.QPushButton(self.tab_4)
        self.cs_list_button.setGeometry(QtCore.QRect(80, 250, 231, 31))
        self.cs_list_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cs_list_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.cs_list_button.setObjectName("cs_list_button")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 461, 421))
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pe_x = QtWidgets.QLineEdit(self.tab_5)
        self.pe_x.setGeometry(QtCore.QRect(180, 160, 61, 23))
        self.pe_x.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pe_x.setObjectName("pe_x")
        self.label_26 = QtWidgets.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(20, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(20, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.start_ang = QtWidgets.QLabel(self.tab_5)
        self.start_ang.setGeometry(QtCore.QRect(20, 220, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start_ang.setFont(font)
        self.start_ang.setStyleSheet("color: rgb(255, 255, 255);")
        self.start_ang.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.start_ang.setObjectName("start_ang")
        self.pe_add_button = QtWidgets.QPushButton(self.tab_5)
        self.pe_add_button.setGeometry(QtCore.QRect(110, 380, 191, 27))
        self.pe_add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pe_add_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.pe_add_button.setObjectName("pe_add_button")
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        self.label_36.setGeometry(QtCore.QRect(350, 160, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(70, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(20, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.pe_length = QtWidgets.QLineEdit(self.tab_5)
        self.pe_length.setGeometry(QtCore.QRect(180, 190, 61, 23))
        self.pe_length.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pe_length.setObjectName("pe_length")
        self.pe_y = QtWidgets.QLineEdit(self.tab_5)
        self.pe_y.setGeometry(QtCore.QRect(280, 160, 61, 23))
        self.pe_y.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pe_y.setObjectName("pe_y")
        self.deg_start = QtWidgets.QLabel(self.tab_5)
        self.deg_start.setGeometry(QtCore.QRect(220, 220, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deg_start.setFont(font)
        self.deg_start.setStyleSheet("color: rgb(255, 255, 255);")
        self.deg_start.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.deg_start.setObjectName("deg_start")
        self.length = QtWidgets.QLabel(self.tab_5)
        self.length.setGeometry(QtCore.QRect(20, 190, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.length.setFont(font)
        self.length.setStyleSheet("color: rgb(255, 255, 255);")
        self.length.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.length.setObjectName("length")
        self.pe_menu = QtWidgets.QComboBox(self.tab_5)
        self.pe_menu.setGeometry(QtCore.QRect(120, 70, 121, 21))
        self.pe_menu.setStyleSheet("border: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color background-gradient;  \n"
"-qt-background-role: base;")
        self.pe_menu.setEditable(False)
        self.pe_menu.setObjectName("pe_menu")
        self.pe_menu.addItem("")
        self.pe_menu.setItemText(0, "")
        self.pe_menu.addItem("")
        self.pe_menu.addItem("")
        self.pe_menu.addItem("")
        self.pe_menu.addItem("")
        self.pe_menu.addItem("")
        self.pe_id = QtWidgets.QLineEdit(self.tab_5)
        self.pe_id.setGeometry(QtCore.QRect(130, 130, 131, 23))
        self.pe_id.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_id.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pe_id.setObjectName("pe_id")
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(20, 160, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.pe_angle = QtWidgets.QLineEdit(self.tab_5)
        self.pe_angle.setGeometry(QtCore.QRect(150, 220, 61, 23))
        self.pe_angle.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_angle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pe_angle.setObjectName("pe_angle")
        self.mm_len = QtWidgets.QLabel(self.tab_5)
        self.mm_len.setGeometry(QtCore.QRect(250, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mm_len.setFont(font)
        self.mm_len.setStyleSheet("color: rgb(255, 255, 255);")
        self.mm_len.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mm_len.setObjectName("mm_len")
        self.pe_group = QtWidgets.QLineEdit(self.tab_5)
        self.pe_group.setGeometry(QtCore.QRect(120, 100, 111, 23))
        self.pe_group.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_group.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pe_group.setObjectName("pe_group")
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(250, 160, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.pe_end_angle = QtWidgets.QLineEdit(self.tab_5)
        self.pe_end_angle.setGeometry(QtCore.QRect(100, 250, 51, 23))
        self.pe_end_angle.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_end_angle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pe_end_angle.setObjectName("pe_end_angle")
        self.deg_end = QtWidgets.QLabel(self.tab_5)
        self.deg_end.setGeometry(QtCore.QRect(160, 250, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deg_end.setFont(font)
        self.deg_end.setStyleSheet("color: rgb(255, 255, 255);")
        self.deg_end.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.deg_end.setObjectName("deg_end")
        self.end_ang = QtWidgets.QLabel(self.tab_5)
        self.end_ang.setGeometry(QtCore.QRect(20, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.end_ang.setFont(font)
        self.end_ang.setStyleSheet("color: rgb(255, 255, 255);")
        self.end_ang.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.end_ang.setObjectName("end_ang")
        self.pe_height = QtWidgets.QLineEdit(self.tab_5)
        self.pe_height.setGeometry(QtCore.QRect(80, 280, 61, 23))
        self.pe_height.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_height.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pe_height.setObjectName("pe_height")
        self.height = QtWidgets.QLabel(self.tab_5)
        self.height.setGeometry(QtCore.QRect(20, 280, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.height.setFont(font)
        self.height.setStyleSheet("color: rgb(255, 255, 255);")
        self.height.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.height.setObjectName("height")
        self.mm_height = QtWidgets.QLabel(self.tab_5)
        self.mm_height.setGeometry(QtCore.QRect(150, 280, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mm_height.setFont(font)
        self.mm_height.setStyleSheet("color: rgb(255, 255, 255);")
        self.mm_height.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mm_height.setObjectName("mm_height")
        self.text = QtWidgets.QLabel(self.tab_5)
        self.text.setGeometry(QtCore.QRect(20, 310, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text.setFont(font)
        self.text.setStyleSheet("color: rgb(255, 255, 255);")
        self.text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text.setObjectName("text")
        self.pe_text = QtWidgets.QLineEdit(self.tab_5)
        self.pe_text.setGeometry(QtCore.QRect(60, 310, 161, 23))
        self.pe_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pe_text.setObjectName("pe_text")
        self.pe_char_space = QtWidgets.QLineEdit(self.tab_5)
        self.pe_char_space.setGeometry(QtCore.QRect(120, 340, 61, 23))
        self.pe_char_space.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_char_space.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pe_char_space.setObjectName("pe_char_space")
        self.char_spac = QtWidgets.QLabel(self.tab_5)
        self.char_spac.setGeometry(QtCore.QRect(20, 340, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.char_spac.setFont(font)
        self.char_spac.setStyleSheet("color: rgb(255, 255, 255);")
        self.char_spac.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.char_spac.setObjectName("char_spac")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_42 = QtWidgets.QLabel(self.tab_6)
        self.label_42.setGeometry(QtCore.QRect(50, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.pe_remove_button = QtWidgets.QPushButton(self.tab_6)
        self.pe_remove_button.setGeometry(QtCore.QRect(280, 200, 121, 51))
        self.pe_remove_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pe_remove_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.pe_remove_button.setObjectName("pe_remove_button")
        self.pe_hide_button = QtWidgets.QPushButton(self.tab_6)
        self.pe_hide_button.setGeometry(QtCore.QRect(20, 200, 121, 51))
        self.pe_hide_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pe_hide_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.pe_hide_button.setObjectName("pe_hide_button")
        self.pe_unhide_button = QtWidgets.QPushButton(self.tab_6)
        self.pe_unhide_button.setGeometry(QtCore.QRect(150, 200, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pe_unhide_button.setFont(font)
        self.pe_unhide_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pe_unhide_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.pe_unhide_button.setObjectName("pe_unhide_button")
        self.pe_menu_2 = QtWidgets.QComboBox(self.tab_6)
        self.pe_menu_2.setGeometry(QtCore.QRect(140, 70, 121, 21))
        self.pe_menu_2.setStyleSheet("border: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color background-gradient;  \n"
"-qt-background-role: base;")
        self.pe_menu_2.setEditable(False)
        self.pe_menu_2.setObjectName("pe_menu_2")
        self.pe_menu_2.addItem("")
        self.pe_menu_2.addItem("")
        self.pe_menu_2.addItem("")
        self.pe_menu_2.addItem("")
        self.pe_menu_2.addItem("")
        self.pe_menu_2.addItem("")
        self.pe_menu_2.setItemText(5, "")
        self.label_44 = QtWidgets.QLabel(self.tab_6)
        self.label_44.setGeometry(QtCore.QRect(30, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_6)
        self.label_45.setGeometry(QtCore.QRect(30, 150, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.pe_group_2 = QtWidgets.QLineEdit(self.tab_6)
        self.pe_group_2.setGeometry(QtCore.QRect(130, 110, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pe_group_2.setFont(font)
        self.pe_group_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_group_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pe_group_2.setObjectName("pe_group_2")
        self.label_46 = QtWidgets.QLabel(self.tab_6)
        self.label_46.setGeometry(QtCore.QRect(30, 110, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.pe_id_2 = QtWidgets.QLineEdit(self.tab_6)
        self.pe_id_2.setGeometry(QtCore.QRect(150, 150, 131, 23))
        self.pe_id_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pe_id_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pe_id_2.setObjectName("pe_id_2")
        self.pe_monitor_button = QtWidgets.QPushButton(self.tab_6)
        self.pe_monitor_button.setGeometry(QtCore.QRect(110, 270, 201, 41))
        self.pe_monitor_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pe_monitor_button.setStyleSheet("border-style: native;\n"
"background-color: native;\n"
"-qt-style-features: background-color;")
        self.pe_monitor_button.setObjectName("pe_monitor_button")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(130, 20, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.pe_menu_2.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Z-Laser Projector GUI"))
        self.start_button.setText(_translate("MainWindow", "Start Projection"))
        self.stop_button.setText(_translate("MainWindow", "Stop Projection"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.disconnect_button.setText(_translate("MainWindow", "Disconnect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "General"))
        self.label_34.setText(_translate("MainWindow", "[mm]"))
        self.label_10.setText(_translate("MainWindow", "y ="))
        self.p2_y.setText(_translate("MainWindow", "-285"))
        self.p2_y.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label.setText(_translate("MainWindow", "Coordinate System Definition"))
        self.label_7.setText(_translate("MainWindow", "Resolution:"))
        self.p3_z.setText(_translate("MainWindow", "0.0"))
        self.p3_z.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_6.setText(_translate("MainWindow", "T1:  x = "))
        self.label_15.setText(_translate("MainWindow", "z ="))
        self.cs_name.setText(_translate("MainWindow", "MY_CS_1"))
        self.cs_name.setPlaceholderText(_translate("MainWindow", "MyCoordinateSystemExample"))
        self.label_9.setText(_translate("MainWindow", "Distance:"))
        self.cs_res.setText(_translate("MainWindow", "1000"))
        self.cs_res.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "[mm]"))
        self.label_11.setText(_translate("MainWindow", "y ="))
        self.t1_y.setText(_translate("MainWindow", "0.0"))
        self.t1_y.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.p3_x.setText(_translate("MainWindow", "525"))
        self.p3_x.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.p4_x.setText(_translate("MainWindow", "-20"))
        self.p4_x.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_12.setText(_translate("MainWindow", "y ="))
        self.p1_z.setText(_translate("MainWindow", "0.0"))
        self.p1_z.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_31.setText(_translate("MainWindow", "[mm]"))
        self.p2_z.setText(_translate("MainWindow", "0.0"))
        self.p2_z.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_18.setText(_translate("MainWindow", "z ="))
        self.label_4.setText(_translate("MainWindow", "P3:  x ="))
        self.label_13.setText(_translate("MainWindow", "y ="))
        self.label_17.setText(_translate("MainWindow", "z ="))
        self.p1_y.setText(_translate("MainWindow", "-285"))
        self.p1_y.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_32.setText(_translate("MainWindow", "[mm]"))
        self.cs_dist.setText(_translate("MainWindow", "1280"))
        self.cs_dist.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "P2:  x ="))
        self.t1_z.setText(_translate("MainWindow", "0.0"))
        self.t1_z.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_19.setText(_translate("MainWindow", "z ="))
        self.p1_x.setText(_translate("MainWindow", "-20"))
        self.p1_x.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_16.setText(_translate("MainWindow", "z ="))
        self.label_2.setText(_translate("MainWindow", "P1:  x ="))
        self.label_14.setText(_translate("MainWindow", "y ="))
        self.label_33.setText(_translate("MainWindow", "[mm]"))
        self.label_8.setText(_translate("MainWindow", "Name:"))
        self.t1_x.setText(_translate("MainWindow", "0.0"))
        self.t1_x.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.p2_x.setText(_translate("MainWindow", "525"))
        self.p2_x.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.p3_y.setText(_translate("MainWindow", "100"))
        self.p3_y.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_35.setText(_translate("MainWindow", "[mm]"))
        self.p4_y.setText(_translate("MainWindow", "100"))
        self.p4_y.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.cs_add_button.setText(_translate("MainWindow", "Add Manual Coordinate System"))
        self.p4_z.setText(_translate("MainWindow", "0.0"))
        self.p4_z.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_5.setText(_translate("MainWindow", "P4:  x = "))
        self.cs_scan_button.setText(_translate("MainWindow", "Add Scanned Coordinate System"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Definition"))
        self.cs_name_handler.setPlaceholderText(_translate("MainWindow", "MyCoordinateSystemExample"))
        self.label_39.setText(_translate("MainWindow", "Name:"))
        self.label_40.setText(_translate("MainWindow", "Seconds:"))
        self.cs_show_secs.setText(_translate("MainWindow", "0"))
        self.cs_show_secs.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_41.setText(_translate("MainWindow", "[seconds]"))
        self.cs_set_button.setText(_translate("MainWindow", "SET"))
        self.label_38.setText(_translate("MainWindow", "Coordinate System Handler"))
        self.cs_show_button.setText(_translate("MainWindow", "SHOW\n"
"ACTIVE"))
        self.cs_remove_button.setText(_translate("MainWindow", "REMOVE"))
        self.cs_list_button.setText(_translate("MainWindow", "Get Coordinate System List"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Manager"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Coord Sys"))
        self.pe_x.setText(_translate("MainWindow", "0.0"))
        self.pe_x.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_26.setText(_translate("MainWindow", "Element type:"))
        self.label_23.setText(_translate("MainWindow", "Group name:"))
        self.start_ang.setText(_translate("MainWindow", "Slope/Start Angle:"))
        self.pe_add_button.setText(_translate("MainWindow", "Add Projection Element"))
        self.label_36.setText(_translate("MainWindow", "{T} ref pos"))
        self.label_21.setText(_translate("MainWindow", "Projection Element Definition"))
        self.label_22.setText(_translate("MainWindow", "Element name:"))
        self.pe_length.setText(_translate("MainWindow", "500.0"))
        self.pe_length.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.pe_y.setText(_translate("MainWindow", "0.0"))
        self.pe_y.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.deg_start.setText(_translate("MainWindow", "[degrees]"))
        self.length.setText(_translate("MainWindow", "Length/Width/Radius:"))
        self.pe_menu.setItemText(1, _translate("MainWindow", "polyline"))
        self.pe_menu.setItemText(2, _translate("MainWindow", "circle"))
        self.pe_menu.setItemText(3, _translate("MainWindow", "arc"))
        self.pe_menu.setItemText(4, _translate("MainWindow", "oval"))
        self.pe_menu.setItemText(5, _translate("MainWindow", "text"))
        self.pe_id.setText(_translate("MainWindow", "figure_a"))
        self.pe_id.setPlaceholderText(_translate("MainWindow", "figure_example"))
        self.label_25.setText(_translate("MainWindow", "Start/center point:  x ="))
        self.pe_angle.setText(_translate("MainWindow", "45.0"))
        self.pe_angle.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.mm_len.setText(_translate("MainWindow", "{T} ref dim"))
        self.pe_group.setText(_translate("MainWindow", "group_1"))
        self.pe_group.setPlaceholderText(_translate("MainWindow", "my_group"))
        self.label_24.setText(_translate("MainWindow", "y ="))
        self.pe_end_angle.setText(_translate("MainWindow", "0.0"))
        self.pe_end_angle.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.deg_end.setText(_translate("MainWindow", "[degrees]"))
        self.end_ang.setText(_translate("MainWindow", "End Angle:"))
        self.pe_height.setText(_translate("MainWindow", "0.0"))
        self.pe_height.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.height.setText(_translate("MainWindow", "Height:"))
        self.mm_height.setText(_translate("MainWindow", "{T} ref dim"))
        self.text.setText(_translate("MainWindow", "Text:"))
        self.pe_text.setPlaceholderText(_translate("MainWindow", "text example"))
        self.pe_char_space.setText(_translate("MainWindow", "0"))
        self.pe_char_space.setPlaceholderText(_translate("MainWindow", "0"))
        self.char_spac.setText(_translate("MainWindow", "Char spacing:"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Definition"))
        self.label_42.setText(_translate("MainWindow", "Projection Elements Handler"))
        self.pe_remove_button.setText(_translate("MainWindow", "REMOVE"))
        self.pe_hide_button.setText(_translate("MainWindow", "HIDE"))
        self.pe_unhide_button.setText(_translate("MainWindow", "UNHIDE"))
        self.pe_menu_2.setItemText(0, _translate("MainWindow", "polyline"))
        self.pe_menu_2.setItemText(1, _translate("MainWindow", "circle"))
        self.pe_menu_2.setItemText(2, _translate("MainWindow", "arc"))
        self.pe_menu_2.setItemText(3, _translate("MainWindow", "oval"))
        self.pe_menu_2.setItemText(4, _translate("MainWindow", "text"))
        self.label_44.setText(_translate("MainWindow", "Element type:"))
        self.label_45.setText(_translate("MainWindow", "Element name:"))
        self.pe_group_2.setText(_translate("MainWindow", "group_1"))
        self.pe_group_2.setPlaceholderText(_translate("MainWindow", "my_group"))
        self.label_46.setText(_translate("MainWindow", "Group name:"))
        self.pe_id_2.setText(_translate("MainWindow", "figure_a"))
        self.pe_id_2.setPlaceholderText(_translate("MainWindow", "figure_example"))
        self.pe_monitor_button.setText(_translate("MainWindow", "Keyboard Monitor"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Manager"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Proj Elements"))
        self.label_37.setText(_translate("MainWindow", "Z - LASER PROJECTOR"))

