# shape_type: keyword of one of the figure types that the laser projector system is able to project:
# - polyline
# - curves: circle, oval, arc (todo)
# - text (todo)
std_msgs/String shape_type

# Group name that the projection element belongs
# Several projection elements can be handled as a projection group
std_msgs/String group_name

# Name of the projection element
std_msgs/String shape_id

---

std_msgs/Bool success
std_msgs/String message