# Name of the coordinate system
string name

# Distance between the projector device and the projection surface
float64 distance

# Real-world coordinates of reference points from the projector's reference system {P}
geometry_msgs/Point[] P

# Coordinates of the reference point T0 from the user's reference system {T}
geometry_msgs/Point T0

# Resolution of the coordinate system
# The resolution is considered for the largest dimension of the coordinate system
# and it is calculated proportionally for the rest
float64 resolution

---

geometry_msgs/Point[] T
bool success
string message