# POLYLINE -> figure_type = 0
# CIRCLE -> figure_type = 1
# ARC -> figure_type = 2
# OVAL -> figure_type = 3
# TEXT -> figure_type = 4
int32 figure_type

# Group name which the projection element belongs
# Several projection elements can be handled as a projection group
string projection_group

# Name of the projection element
string figure_name

---

bool success
string message